spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydb.mysql.database.azure.com:3306/mydb?reconnect=true
    username: yyds
    password: comp30022-
    schema: classpath:db/schema-test.sql
    data: classpath:db/data-test.sql
    initialization-mode: always

  #jackson
  jackson:
    property-naming-strategy: SNAKE_CASE

  #mail config
  mail:
    host: smtp.gmail.com
    username: connecti.yyds@gmail.com
    password: ysqujsagxxfyqwvm
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    from: connecti.yyds@gmail.com
    default-encoding: utf-8

  mvc:
    log-resolved-exception: true



mybatis-plus:
  typeEnumsPackage: tech.crm.crmserver.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl