spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydb.mysql.database.azure.com:3306/mydb?reconnect=true
    username: yyds
    password: comp30022-
  mvc:
    log-resolved-exception: true

  #mail config
  mail:
    host: smtp.gmail.com
    username: connecti.yyds@gmail.com
    password: ysqujsagxxfyqwvm
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    from: connecti.yyds@gmail.com
    default-encoding: utf-8


mybatis-plus:
  typeEnumsPackage: tech.crm.crmserver.common.enums

