spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydb.mysql.database.azure.com:3306/mydb?reconnect=true&serverTimezone=Australia/Victoria
    username: yyds
    password: comp30022-
  mvc:
    log-resolved-exception: true


  #jackson
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+10

  #mail config
  mail:
    host: smtp.gmail.com
    username: connecti.yyds@gmail.com
    password: ysqujsagxxfyqwvm
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
    #send email from which mail
    from: connecti.yyds@gmail.com
    #url for active account
    active: https://comp30022-yyds.herokuapp.com/verify
    default-encoding: utf-8


mybatis-plus:
  typeEnumsPackage: tech.crm.crmserver.common.enums
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

